# 1. Standard Scaling

`Standard scaling` is a technique used in data preprocessing to normalize the features of a dataset. It transforms the data so that it has a mean of 0 and a standard deviation of 1. This is particularly useful for algorithms that are sensitive to the scale of the data, such as gradient descent-based methods.

the formula is as follows:

z = (x - μ) / σ
Where:
- z is the standardized value
- x is the original value
- μ is the mean of the feature
- σ is the standard deviation of the feature

In [1]:
# import libraries
import pandas as pd 
from sklearn.preprocessing import StandardScaler

In [2]:
# make an example dataset
df = {
    'age': [25, 30, 35, 40, 45],
    'height': [165, 170, 175, 180, 185],
    'weight': [55, 60, 65, 70, 75]
}

# convert the dataset into a pandas DataFrame
df = pd.DataFrame(df)
df.head()

   age  height  weight
0   25     165      55
1   30     170      60
2   35     175      65
3   40     180      70
4   45     185      75

In [3]:
# import the scaler 
scaler = StandardScaler()

# fit the scaler to the data
scaled_df = scaler.fit_transform(df)
scaled_df

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])

In [4]:
# convert this data into a pandas DataFrame
scaled_df = pd.DataFrame(scaled_df, columns=df.columns)
scaled_df.head()

        age    height    weight
0 -1.414214 -1.414214 -1.414214
1 -0.707107 -0.707107 -0.707107
2  0.000000  0.000000  0.000000
3  0.707107  0.707107  0.707107
4  1.414214  1.414214  1.414214