# Plotly Data Visualization (part-1)

In [ ]:
# install plotly
# !pip install plotly
# pip install -U kaleido
# check others modules errors if happens an

Requirement already satisfied: plotly in c:\users\zone tech\miniconda3\envs\python_eda\lib\site-packages (6.5.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\zone tech\miniconda3\envs\python_eda\lib\site-packages (from plotly) (2.17.0)
Requirement already satisfied: packaging in c:\users\zone tech\miniconda3\envs\python_eda\lib\site-packages (from plotly) (25.0)

In [11]:
# import libraries
import pandas as pd
import numpy as np 
import seaborn as sns  
import plotly.express as px

In [ ]:
names = ['M Abdul Basit', 'Hamza', 'Arshad']
heights = [5.8, 5.9, 5.7]

# create a plot (line plot)
fig = px.line(x=names, y=heights, title='Heights of Individuals')

# show thw fig
fig.show()

# save the plot in phg file
fig.write_image('./outputs/01_lineplot.png')

# save as standalone html file
fig.write_html('./outputs/01_lineplot.html')

In [20]:
names = ['M Abdul Basit', 'Hamza', 'Arshad']
heights = [5.8, 5.9, 5.7]

# create a plot (line plot)
fig = px.bar(x=names, y=heights, title='Heights of Individuals')

# show the figure
fig.show()

# save the plot in png file
fig.write_image('./outputs/01_barplot.png')

# save as standalone html file
fig.write_html('./outputs/01_barplot.html')

# Plots On titanic Dataset

In [21]:
# import dataset
df = sns.load_dataset('titanic')
# check the head of dataset
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# scatter plot

# if the nan values available in  the daraset then how i can remove the nan values from the dataset
# df.dropna(inplace=True)
fig  = px.scatter(df, x='age', y='fare', color='sex', size='fare', title='Plot of Age vs Fare of titanic Dataset')
fig.show()

In [31]:
# scatter plot

# if the nan values available in  the daraset then how i can remove the nan values from the dataset
df.dropna(inplace=True)

fig  = px.scatter(df, x='age', y='fare', color='sex', size='age', title='Plot of Age vs Fare of titanic Dataset')
fig.show()

# save the plot in the png file
fig.write_image('./outputs/01_scatterplot.png', scale=3)

 # how to save in 300 dpi resolution
fig.write_image('./outputs/01_scatterplot_300dpi.png', scale=3, width=800, height=600)

# save file in the json format
fig.write_json('./outputs/01_scatterplot.json')

In [37]:
import plotly.graph_objects as go

# create a simple line chart
fig = go.Figure(data=go.Scatter(x=[1, 2, 3, 4], y=[10, 11, 12, 13]))
fig.show()

In [38]:
# custimize/Update the plot

fig.update_layout(
    title = 'Line Chart Plot Of Dummy Data',
    xaxis = dict(title='Numbers'),
    yaxis = dict(title='Values'),
    showlegend = True,
    #font=dict(family='Arial', size=14, color='blue')
)
fig.show()

In [ ]:
# heatmap in Plotly

data = np.random.rand(10, 10)
heatmap = go.Heatmap(z=data)
fig = go.Figure(data=heatmap)
fig.show()

In [ ]:
df[['age', 'fare']].corr()

          age     fare
age   1.00000 -0.09073
fare -0.09073  1.00000

In [47]:
# heatmap on corr of titanic dataset of age and fare using plotly

fig = px.imshow(df[['age', 'fare']].corr(), title='Correlation Heatmap of Age and Fare')
fig.show()

In [42]:
# iris dataset 
iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [45]:
# heatmap on corr of iris dataset using plotly

fig = px.imshow(iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].corr())
fig.show()